### ISSUE TITLE
Controlar o volume do script

### ISSUE THREAD

**Issue by sneffetsd** [lnpbr/BlueprintsHA#1]
Seria possível adicionar uma opção no blueprint para escolher o volume do anúncio na alexa?

**Comment by lnpbr** [comment]
Sim, manda reimportar o blueprint, e já estará lá a opção, acabei de atualizar....
O volume padrão é 90%, ou seja, se não escolher o volume, fica em 90%...

**Comment by sneffetsd** [comment]
Perfeito. Funcionando.
